GAME_WIDTH = 640
GAME_HEIGHT = 480
BACKGROUND_COLOR = (224, 224, 224)

TILE_COLOR = (64, 64, 128)
TILE_SHADE_COLOR = (16, 16, 32)
TILE_SHADE_OFFSET = 4
TILE_WIDTH = 32
TILE_HEIGHT = 32
TILE_BORDER_RADIUS = 8
TILE_OFFSET = 1

BOX_SLOT_COLOR = (192, 0, 0)
BOX_SLOT_WIDTH = 20
BOX_SLOT_HEIGHT = 20
BOX_SLOT_BORDER_RADIUS = 2
BOX_SLOT_FRAME_WIDTH = 2

BOX_COLOR = (192, 96, 0)
BOX_SHADE_COLOR = (128, 32, 0)
BOX_SHADE_OFFSET = 2
BOX_WIDTH = 16
BOX_HEIGHT = 16
BOX_BORDER_RADIUS = 4

PLAYER_COLOR = (128, 192, 128)
PLAYER_SHADE_COLOR = (64, 128, 64)
PLAYER_SHADE_OFFSET = 2
PLAYER_RADIUS = 12
PLAYER_UP_MOVEMENT_KEY = "w"
PLAYER_DOWN_MOVEMENT_KEY = "s"
PLAYER_LEFT_MOVEMENT_KEY = "a"
PLAYER_RIGHT_MOVEMENT_KEY = "d"

LEVEL_RESTART_KEY = "r"

UI_TEXT_FONT = "arial.ttf"
UI_TEXT_COLOR = (32, 32, 32)
UI_TEXT_FONT_SIZE = 32

LEVEL_TEXT = "LEVEL"
MOVES_TEXT = "Moves"
BOXES_TEXT = "Boxes"

LEVEL_FILES = ("level1.csv", "level2.csv")
LEVEL_FILES_FOLDER = "levels"